create extension if not exists btree_gist;

do $$ begin create type public.rol_usuario as enum ('admin','medico','recepcionista','paciente','enfermero'); exception when duplicate_object then null; end $$;
do $$ begin create type public.estado_cita as enum ('pendiente','confirmada','cancelada_paciente','cancelada_medico','atendida','no_asistio'); exception when duplicate_object then null; end $$;
do $$ begin create type public.estado_internacion as enum ('activa','alta','traslado'); exception when duplicate_object then null; end $$;
do $$ begin create type public.tipo_orden_medica as enum ('analisis','medicamento','tratamiento','procedimiento'); exception when duplicate_object then null; end $$;
do $$ begin create type public.estado_orden as enum ('prescrita','en_proceso','realizada','cancelada'); exception when duplicate_object then null; end $$;

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  correo varchar(150) not null unique,
  nombre_completo varchar(200) not null,
  telefono varchar(20),
  rol public.rol_usuario not null default 'paciente',
  esta_activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.clinicas (
  id bigint generated by default as identity primary key,
  nombre varchar(200) not null,
  direccion text,
  telefono varchar(20),
  correo_contacto varchar(150),
  esta_activo boolean not null default true,
  archivado_en timestamptz
);

create table if not exists public.perfiles_medicos (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  clinica_id bigint not null references public.clinicas(id) on delete restrict,
  especialidad varchar(150) not null,
  cedula_profesional varchar(50) not null unique,
  duracion_consulta integer not null default 20,
  esta_activo boolean not null default true,
  archivado_en timestamptz,
  unique(usuario_id, clinica_id),
  unique(id, clinica_id)
);

create table if not exists public.perfiles_pacientes (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null unique references public.usuarios(id) on delete cascade,
  fecha_nacimiento date,
  genero char(1),
  nombre_contacto_emergencia varchar(200),
  telefono_emergencia varchar(20),
  notas_medicas text,
  esta_activo boolean not null default true,
  archivado_en timestamptz
);

create table if not exists public.perfiles_enfermeros (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  clinica_id bigint not null references public.clinicas(id) on delete restrict,
  especialidad varchar(100),
  esta_activo boolean not null default true,
  archivado_en timestamptz
);

create table if not exists public.citas (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.perfiles_pacientes(id) on delete cascade,
  medico_id bigint not null,
  clinica_id bigint not null,
  inicio timestamptz not null,
  fin timestamptz not null,
  estado public.estado_cita not null default 'pendiente',
  motivo text,
  motivo_cancelacion text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  foreign key (medico_id, clinica_id) references public.perfiles_medicos(id, clinica_id) on delete restrict,
  constraint citas_horario_valido check (fin > inicio)
);

create table if not exists public.expedientes (
  id bigint generated by default as identity primary key,
  cita_id bigint not null unique references public.citas(id) on delete cascade,
  diagnostico text,
  receta text,
  notas_doctor text,
  creado_en timestamptz not null default now()
);

create table if not exists public.habitaciones (
  id bigint generated by default as identity primary key,
  clinica_id bigint not null references public.clinicas(id) on delete cascade,
  numero varchar(20) not null,
  tipo varchar(50) not null,
  capacidad integer not null default 1,
  unique(clinica_id, numero),
  constraint habitaciones_capacidad_valida check (capacidad > 0)
);

create table if not exists public.camas (
  id bigint generated by default as identity primary key,
  habitacion_id bigint not null references public.habitaciones(id) on delete cascade,
  numero varchar(20) not null,
  esta_ocupada boolean not null default false,
  unique(habitacion_id, numero)
);

create table if not exists public.internaciones (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.perfiles_pacientes(id) on delete restrict,
  clinica_id bigint not null references public.clinicas(id) on delete restrict,
  medico_responsable_id bigint not null references public.perfiles_medicos(id) on delete restrict,
  habitacion_id bigint not null references public.habitaciones(id) on delete restrict,
  cama_id bigint not null references public.camas(id) on delete restrict,
  fecha_ingreso timestamptz not null default now(),
  fecha_alta timestamptz,
  estado public.estado_internacion not null default 'activa',
  motivo_ingreso text,
  diagnostico_ingreso text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.episodios_medicos (
  id bigint generated by default as identity primary key,
  internacion_id bigint not null references public.internaciones(id) on delete cascade,
  medico_id bigint references public.perfiles_medicos(id) on delete set null,
  enfermero_id bigint references public.perfiles_enfermeros(id) on delete set null,
  fecha_hora timestamptz not null default now(),
  tipo_episodio varchar(50) not null,
  descripcion text,
  presion_arterial varchar(20),
  frecuencia_cardiaca integer,
  temperatura numeric(4,1),
  otros_signos jsonb
);

create table if not exists public.ordenes_medicas (
  id bigint generated by default as identity primary key,
  episodio_id bigint not null references public.episodios_medicos(id) on delete cascade,
  tipo_orden public.tipo_orden_medica not null,
  descripcion text not null,
  instrucciones text,
  estado public.estado_orden not null default 'prescrita',
  fecha_prescripcion timestamptz not null default now(),
  fecha_ejecucion timestamptz,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.catalogo_analisis (
  id bigint generated by default as identity primary key,
  nombre varchar(100) not null unique,
  descripcion text,
  requiere_ayuno boolean not null default false,
  tiempo_resultado_horas integer
);

create table if not exists public.solicitudes_analisis (
  id bigint generated by default as identity primary key,
  orden_medica_id bigint not null references public.ordenes_medicas(id) on delete cascade,
  analisis_id bigint not null references public.catalogo_analisis(id) on delete restrict,
  fecha_solicitud timestamptz not null default now(),
  fecha_toma_muestra timestamptz,
  enfermero_toma_id bigint references public.perfiles_enfermeros(id) on delete set null,
  fecha_resultado timestamptz,
  resultado text,
  archivo_resultado varchar(255),
  estado_analisis varchar(30) not null default 'solicitado',
  observaciones text
);

create index if not exists idx_usuarios_auth_user_id on public.usuarios(auth_user_id);
create index if not exists idx_citas_paciente_id on public.citas(paciente_id);
create index if not exists idx_citas_medico_inicio on public.citas(medico_id, inicio);
create index if not exists idx_citas_clinica_inicio on public.citas(clinica_id, inicio);
create index if not exists idx_internaciones_paciente on public.internaciones(paciente_id);
create index if not exists idx_internaciones_estado on public.internaciones(estado);
create index if not exists idx_episodios_internacion on public.episodios_medicos(internacion_id);
create index if not exists idx_ordenes_episodio on public.ordenes_medicas(episodio_id);
create index if not exists idx_solicitudes_orden on public.solicitudes_analisis(orden_medica_id);

alter table public.usuarios enable row level security;
alter table public.clinicas enable row level security;
alter table public.perfiles_medicos enable row level security;
alter table public.perfiles_pacientes enable row level security;
alter table public.perfiles_enfermeros enable row level security;
alter table public.citas enable row level security;
alter table public.expedientes enable row level security;
alter table public.habitaciones enable row level security;
alter table public.camas enable row level security;
alter table public.internaciones enable row level security;
alter table public.episodios_medicos enable row level security;
alter table public.ordenes_medicas enable row level security;
alter table public.catalogo_analisis enable row level security;
alter table public.solicitudes_analisis enable row level security;

drop policy if exists usuarios_self_select on public.usuarios;
create policy usuarios_self_select on public.usuarios for select to authenticated
  using (auth_user_id = (select auth.uid()));

drop policy if exists usuarios_self_update on public.usuarios;
create policy usuarios_self_update on public.usuarios for update to authenticated
  using (auth_user_id = (select auth.uid()))
  with check (auth_user_id = (select auth.uid()));

drop policy if exists pacientes_self_select on public.perfiles_pacientes;
create policy pacientes_self_select on public.perfiles_pacientes for select to authenticated
  using (usuario_id in (select id from public.usuarios where auth_user_id = (select auth.uid())));

drop policy if exists citas_authenticated_select on public.citas;
create policy citas_authenticated_select on public.citas for select to authenticated using (true);

drop policy if exists citas_authenticated_insert on public.citas;
create policy citas_authenticated_insert on public.citas for insert to authenticated with check (true);

drop policy if exists citas_authenticated_update on public.citas;
create policy citas_authenticated_update on public.citas for update to authenticated using (true) with check (true);

drop policy if exists catalogo_authenticated_select on public.catalogo_analisis;
create policy catalogo_authenticated_select on public.catalogo_analisis for select to authenticated using (true);

select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in (
    'usuarios','clinicas','perfiles_medicos','perfiles_pacientes',
    'perfiles_enfermeros','citas','expedientes','habitaciones','camas',
    'internaciones','episodios_medicos','ordenes_medicas',
    'catalogo_analisis','solicitudes_analisis'
  )
order by table_name;

