-- ==============================================================================
-- Clínica Nova · Esquema completo y datos iniciales para Supabase
-- ==============================================================================

create extension if not exists btree_gist;

-- Tipos enumerados
do $$ begin create type public.rol_usuario as enum ('admin','medico','recepcionista','paciente','enfermero'); exception when duplicate_object then null; end $$;
do $$ begin create type public.estado_cita as enum ('pendiente','confirmada','cancelada_paciente','cancelada_medico','atendida','no_asistio'); exception when duplicate_object then null; end $$;
do $$ begin create type public.estado_internacion as enum ('activa','alta','traslado'); exception when duplicate_object then null; end $$;
do $$ begin create type public.tipo_orden_medica as enum ('analisis','medicamento','tratamiento','procedimiento'); exception when duplicate_object then null; end $$;
do $$ begin create type public.estado_orden as enum ('prescrita','en_proceso','realizada','cancelada'); exception when duplicate_object then null; end $$;

-- 1. Tabla Usuarios
create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  correo varchar(150) not null unique,
  nombre_completo varchar(200) not null,
  telefono varchar(20),
  rol public.rol_usuario not null default 'paciente',
  esta_activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

-- 2. Tabla Clínicas
create table if not exists public.clinicas (
  id bigint generated by default as identity primary key,
  nombre varchar(200) not null,
  direccion text,
  telefono varchar(20),
  correo_contacto varchar(150),
  esta_activo boolean not null default true,
  archivado_en timestamptz
);

-- 3. Tabla Perfiles Médicos
create table if not exists public.perfiles_medicos (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  clinica_id bigint not null references public.clinicas(id) on delete restrict,
  especialidad varchar(150) not null,
  cedula_profesional varchar(50) not null unique,
  duracion_consulta integer not null default 20,
  esta_activo boolean not null default true,
  archivado_en timestamptz,
  unique(usuario_id, clinica_id),
  unique(id, clinica_id)
);

-- 4. Tabla Perfiles Pacientes
create table if not exists public.perfiles_pacientes (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null unique references public.usuarios(id) on delete cascade,
  fecha_nacimiento date,
  genero char(1),
  nombre_contacto_emergencia varchar(200),
  telefono_emergencia varchar(20),
  notas_medicas text,
  esta_activo boolean not null default true,
  archivado_en timestamptz
);

-- 5. Tabla Perfiles Enfermeros
create table if not exists public.perfiles_enfermeros (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  clinica_id bigint not null references public.clinicas(id) on delete restrict,
  especialidad varchar(100),
  esta_activo boolean not null default true,
  archivado_en timestamptz
);

-- 6. Tabla Citas
create table if not exists public.citas (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.perfiles_pacientes(id) on delete cascade,
  medico_id bigint not null,
  clinica_id bigint not null,
  inicio timestamptz not null,
  fin timestamptz not null,
  estado public.estado_cita not null default 'pendiente',
  motivo text,
  motivo_cancelacion text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  foreign key (medico_id, clinica_id) references public.perfiles_medicos(id, clinica_id) on delete restrict,
  constraint citas_horario_valido check (fin > inicio)
);

-- 7. Tabla Expedientes
create table if not exists public.expedientes (
  id bigint generated by default as identity primary key,
  cita_id bigint not null unique references public.citas(id) on delete cascade,
  diagnostico text,
  receta text,
  notas_doctor text,
  creado_en timestamptz not null default now()
);

-- 8. Habitaciones y Camas
create table if not exists public.habitaciones (
  id bigint generated by default as identity primary key,
  clinica_id bigint not null references public.clinicas(id) on delete cascade,
  numero varchar(20) not null,
  tipo varchar(50) not null,
  capacidad integer not null default 1,
  unique(clinica_id, numero),
  constraint habitaciones_capacidad_valida check (capacidad > 0)
);

create table if not exists public.camas (
  id bigint generated by default as identity primary key,
  habitacion_id bigint not null references public.habitaciones(id) on delete cascade,
  numero varchar(20) not null,
  esta_ocupada boolean not null default false,
  unique(habitacion_id, numero)
);

-- 9. Internaciones y Episodios
create table if not exists public.internaciones (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.perfiles_pacientes(id) on delete restrict,
  clinica_id bigint not null references public.clinicas(id) on delete restrict,
  medico_responsable_id bigint not null references public.perfiles_medicos(id) on delete restrict,
  habitacion_id bigint not null references public.habitaciones(id) on delete restrict,
  cama_id bigint not null references public.camas(id) on delete restrict,
  fecha_ingreso timestamptz not null default now(),
  fecha_alta timestamptz,
  estado public.estado_internacion not null default 'activa',
  motivo_ingreso text,
  diagnostico_ingreso text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.episodios_medicos (
  id bigint generated by default as identity primary key,
  internacion_id bigint not null references public.internaciones(id) on delete cascade,
  medico_id bigint references public.perfiles_medicos(id) on delete set null,
  enfermero_id bigint references public.perfiles_enfermeros(id) on delete set null,
  fecha_hora timestamptz not null default now(),
  tipo_episodio varchar(50) not null,
  descripcion text,
  presion_arterial varchar(20),
  frecuencia_cardiaca integer,
  temperatura numeric(4,1),
  otros_signos jsonb
);

-- 10. Órdenes Médicas y Laboratorio
create table if not exists public.ordenes_medicas (
  id bigint generated by default as identity primary key,
  episodio_id bigint references public.episodios_medicos(id) on delete set null,
  paciente_id bigint references public.perfiles_pacientes(id) on delete cascade,
  medico_id bigint references public.perfiles_medicos(id) on delete set null,
  tipo_orden public.tipo_orden_medica not null,
  descripcion text not null,
  instrucciones text,
  estado public.estado_orden not null default 'prescrita',
  fecha_prescripcion timestamptz not null default now(),
  fecha_ejecucion timestamptz,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.catalogo_analisis (
  id bigint generated by default as identity primary key,
  nombre varchar(100) not null unique,
  descripcion text,
  requiere_ayuno boolean not null default false,
  tiempo_resultado_horas integer
);

create table if not exists public.solicitudes_analisis (
  id bigint generated by default as identity primary key,
  orden_medica_id bigint references public.ordenes_medicas(id) on delete cascade,
  paciente_id bigint references public.perfiles_pacientes(id) on delete cascade,
  analisis_id bigint not null references public.catalogo_analisis(id) on delete restrict,
  fecha_solicitud timestamptz not null default now(),
  fecha_toma_muestra timestamptz,
  enfermero_toma_id bigint references public.perfiles_enfermeros(id) on delete set null,
  fecha_resultado timestamptz,
  resultado text,
  archivo_resultado varchar(255),
  estado_analisis varchar(30) not null default 'solicitado',
  observaciones text
);

-- Índices principales
create index if not exists idx_usuarios_auth_user_id on public.usuarios(auth_user_id);
create index if not exists idx_citas_paciente_id on public.citas(paciente_id);
create index if not exists idx_citas_medico_inicio on public.citas(medico_id, inicio);
create index if not exists idx_citas_clinica_inicio on public.citas(clinica_id, inicio);
create index if not exists idx_internaciones_paciente on public.internaciones(paciente_id);
create index if not exists idx_internaciones_estado on public.internaciones(estado);
create index if not exists idx_episodios_internacion on public.episodios_medicos(internacion_id);
create index if not exists idx_ordenes_episodio on public.ordenes_medicas(episodio_id);
create index if not exists idx_solicitudes_orden on public.solicitudes_analisis(orden_medica_id);

-- ==============================================================================
-- Políticas RLS (Seguridad a nivel de fila)
-- ==============================================================================

alter table public.usuarios enable row level security;
alter table public.clinicas enable row level security;
alter table public.perfiles_medicos enable row level security;
alter table public.perfiles_pacientes enable row level security;
alter table public.perfiles_enfermeros enable row level security;
alter table public.citas enable row level security;
alter table public.expedientes enable row level security;
alter table public.habitaciones enable row level security;
alter table public.camas enable row level security;
alter table public.internaciones enable row level security;
alter table public.episodios_medicos enable row level security;
alter table public.ordenes_medicas enable row level security;
alter table public.catalogo_analisis enable row level security;
alter table public.solicitudes_analisis enable row level security;

-- Borrar políticas previas para evitar duplicados
drop policy if exists usuarios_authenticated on public.usuarios;
drop policy if exists clinicas_authenticated on public.clinicas;
drop policy if exists perfiles_medicos_authenticated on public.perfiles_medicos;
drop policy if exists perfiles_pacientes_authenticated on public.perfiles_pacientes;
drop policy if exists perfiles_enfermeros_authenticated on public.perfiles_enfermeros;
drop policy if exists citas_authenticated on public.citas;
drop policy if exists expedientes_authenticated on public.expedientes;
drop policy if exists habitaciones_authenticated on public.habitaciones;
drop policy if exists camas_authenticated on public.camas;
drop policy if exists internaciones_authenticated on public.internaciones;
drop policy if exists episodios_medicos_authenticated on public.episodios_medicos;
drop policy if exists ordenes_medicas_authenticated on public.ordenes_medicas;
drop policy if exists catalogo_analisis_authenticated on public.catalogo_analisis;
drop policy if exists solicitudes_analisis_authenticated on public.solicitudes_analisis;

-- Políticas completas para usuarios autenticados del sistema clínico
create policy usuarios_authenticated on public.usuarios for all to authenticated using (true) with check (true);
create policy clinicas_authenticated on public.clinicas for all to authenticated using (true) with check (true);
create policy perfiles_medicos_authenticated on public.perfiles_medicos for all to authenticated using (true) with check (true);
create policy perfiles_pacientes_authenticated on public.perfiles_pacientes for all to authenticated using (true) with check (true);
create policy perfiles_enfermeros_authenticated on public.perfiles_enfermeros for all to authenticated using (true) with check (true);
create policy citas_authenticated on public.citas for all to authenticated using (true) with check (true);
create policy expedientes_authenticated on public.expedientes for all to authenticated using (true) with check (true);
create policy habitaciones_authenticated on public.habitaciones for all to authenticated using (true) with check (true);
create policy camas_authenticated on public.camas for all to authenticated using (true) with check (true);
create policy internaciones_authenticated on public.internaciones for all to authenticated using (true) with check (true);
create policy episodios_medicos_authenticated on public.episodios_medicos for all to authenticated using (true) with check (true);
create policy ordenes_medicas_authenticated on public.ordenes_medicas for all to authenticated using (true) with check (true);
create policy catalogo_analisis_authenticated on public.catalogo_analisis for all to authenticated using (true) with check (true);
create policy solicitudes_analisis_authenticated on public.solicitudes_analisis for all to authenticated using (true) with check (true);

-- ==============================================================================
-- Trigger para sincronizar automáticamente altas de Auth con la tabla usuarios
-- ==============================================================================

create or replace function public.handle_new_auth_user()
returns trigger as $$
begin
  insert into public.usuarios (auth_user_id, correo, nombre_completo, rol)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'nombre_completo', split_part(new.email, '@', 1)),
    case 
      when new.raw_user_meta_data->>'rol' in ('admin','medico','recepcionista','paciente','enfermero') 
      then (new.raw_user_meta_data->>'rol')::public.rol_usuario
      else 'admin'::public.rol_usuario
    end
  )
  on conflict (correo) do update
  set auth_user_id = new.id,
      nombre_completo = coalesce(excluded.nombre_completo, public.usuarios.nombre_completo);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

-- ==============================================================================
-- Datos Semilla (Seed Data)
-- ==============================================================================

-- 1. Vincular usuarios existentes de Auth a la tabla usuarios
insert into public.usuarios (auth_user_id, correo, nombre_completo, rol)
select
  id,
  email,
  coalesce(raw_user_meta_data->>'nombre_completo', 'Diego Ramírez'),
  'admin'::public.rol_usuario
from auth.users
on conflict (correo) do update
set auth_user_id = excluded.auth_user_id;

-- 2. Clínica Principal
insert into public.clinicas (id, nombre, direccion, telefono, correo_contacto)
values (1, 'Clínica Nova - Sede Central', 'Av. Central Poniente 1234, Tuxtla Gutiérrez, Chiapas', '961-123-4567', 'contacto@clinicanova.com')
on conflict (id) do nothing;

-- 3. Médicos iniciales
insert into public.usuarios (id, correo, nombre_completo, telefono, rol)
values 
  (101, 'ana.lopez@clinicanova.com', 'Dra. Ana López', '961-111-2233', 'medico'),
  (102, 'jorge.mendez@clinicanova.com', 'Dr. Jorge Méndez', '961-222-3344', 'medico'),
  (103, 'laura.ruiz@clinicanova.com', 'Dra. Laura Ruiz', '961-333-4455', 'medico')
on conflict (correo) do update set nombre_completo = excluded.nombre_completo;

insert into public.perfiles_medicos (id, usuario_id, clinica_id, especialidad, cedula_profesional, duracion_consulta, esta_activo)
values
  (1, 101, 1, 'Medicina general', 'CED-100234', 20, true),
  (2, 102, 1, 'Cardiología', 'CED-200567', 30, true),
  (3, 103, 1, 'Medicina interna', 'CED-300891', 30, true)
on conflict (id) do nothing;

-- 4. Pacientes iniciales
insert into public.usuarios (id, correo, nombre_completo, telefono, rol)
values
  (201, 'mariana.torres@gmail.com', 'Mariana Torres', '961-123-1235', 'paciente'),
  (202, 'carlos.ramirez@gmail.com', 'Carlos Ramírez', '961-123-1236', 'paciente'),
  (203, 'sofia.hernandez@gmail.com', 'Sofía Hernández', '961-123-1237', 'paciente'),
  (204, 'roberto.garcia@gmail.com', 'Roberto García', '961-123-1238', 'paciente')
on conflict (correo) do update set nombre_completo = excluded.nombre_completo;

insert into public.perfiles_pacientes (id, usuario_id, fecha_nacimiento, genero, esta_activo)
values
  (1, 201, '1992-05-14', 'F', true),
  (2, 202, '1985-08-22', 'M', true),
  (3, 203, '1998-11-03', 'F', true),
  (4, 204, '1976-03-30', 'M', true)
on conflict (id) do nothing;

-- 5. Habitaciones y Camas
insert into public.habitaciones (id, clinica_id, numero, tipo, capacidad)
values
  (1, 1, 'Habitación 101', 'Individual', 1),
  (2, 1, 'Habitación 102', 'Individual', 1),
  (3, 1, 'Habitación 103', 'Doble', 2),
  (4, 1, 'Habitación 104', 'Terapia intensiva', 1)
on conflict (id) do nothing;

insert into public.camas (id, habitacion_id, numero, esta_ocupada)
values
  (1, 1, 'Cama 101-A', true),
  (2, 2, 'Cama 102-A', true),
  (3, 3, 'Cama 103-A', false),
  (4, 3, 'Cama 103-B', false),
  (5, 4, 'Cama UCI-1', false)
on conflict (id) do nothing;

-- 6. Citas iniciales
insert into public.citas (id, paciente_id, medico_id, clinica_id, inicio, fin, estado, motivo)
values
  (1, 1, 1, 1, date_trunc('day', now()) + time '08:30:00', date_trunc('day', now()) + time '09:00:00', 'confirmada', 'Consulta general'),
  (2, 2, 2, 1, date_trunc('day', now()) + time '09:00:00', date_trunc('day', now()) + time '09:30:00', 'pendiente', 'Cardiología'),
  (3, 3, 1, 1, date_trunc('day', now()) + time '09:30:00', date_trunc('day', now()) + time '10:00:00', 'confirmada', 'Seguimiento'),
  (4, 4, 3, 1, date_trunc('day', now()) + time '10:00:00', date_trunc('day', now()) + time '10:30:00', 'pendiente', 'Control clínico')
on conflict (id) do nothing;

-- 7. Expedientes
insert into public.expedientes (id, cita_id, diagnostico, receta, notas_doctor)
values
  (1, 1, 'Hipertensión controlada', 'Losartán 50mg cada 24 hrs', 'Paciente evoluciona favorablemente.'),
  (2, 2, 'Arritmia leve', 'Propranolol 40mg', 'Programar holter de 24 horas.')
on conflict (id) do nothing;

-- 8. Catálogo de Análisis y Órdenes
insert into public.catalogo_analisis (id, nombre, descripcion, requiere_ayuno, tiempo_resultado_horas)
values
  (1, 'Biometría hemática', 'Conteo completo de células sanguíneas', true, 12),
  (2, 'Perfil lipídico', 'Colesterol total, HDL, LDL y triglicéridos', true, 24),
  (3, 'Glucosa en ayuno', 'Nivel de glucosa en plasma', true, 8)
on conflict (id) do nothing;

insert into public.ordenes_medicas (id, paciente_id, medico_id, tipo_orden, descripcion, instrucciones, estado)
values
  (1, 2, 2, 'analisis', 'Electrocardiograma', 'Reposo previo de 15 minutos', 'prescrita'),
  (2, 1, 1, 'analisis', 'Biometría hemática', 'Ayuno de 8 horas', 'en_proceso'),
  (3, 3, 1, 'procedimiento', 'Radiografía de tórax', 'Retirar objetos metálicos', 'realizada')
on conflict (id) do nothing;

insert into public.solicitudes_analisis (id, orden_medica_id, paciente_id, analisis_id, estado_analisis, observaciones)
values
  (1, 2, 1, 1, 'en_proceso', 'Muestra tomada en laboratorio central'),
  (2, null, 2, 2, 'solicitado', 'Pendiente de toma de muestra')
on conflict (id) do nothing;

-- Ajustar secuencias autoincrementales
select setval(pg_get_serial_sequence('public.usuarios', 'id'), coalesce(max(id), 1) + 10) from public.usuarios;
select setval(pg_get_serial_sequence('public.clinicas', 'id'), coalesce(max(id), 1) + 10) from public.clinicas;
select setval(pg_get_serial_sequence('public.perfiles_medicos', 'id'), coalesce(max(id), 1) + 10) from public.perfiles_medicos;
select setval(pg_get_serial_sequence('public.perfiles_pacientes', 'id'), coalesce(max(id), 1) + 10) from public.perfiles_pacientes;
select setval(pg_get_serial_sequence('public.habitaciones', 'id'), coalesce(max(id), 1) + 10) from public.habitaciones;
select setval(pg_get_serial_sequence('public.camas', 'id'), coalesce(max(id), 1) + 10) from public.camas;
select setval(pg_get_serial_sequence('public.citas', 'id'), coalesce(max(id), 1) + 10) from public.citas;
select setval(pg_get_serial_sequence('public.expedientes', 'id'), coalesce(max(id), 1) + 10) from public.expedientes;
select setval(pg_get_serial_sequence('public.ordenes_medicas', 'id'), coalesce(max(id), 1) + 10) from public.ordenes_medicas;
select setval(pg_get_serial_sequence('public.catalogo_analisis', 'id'), coalesce(max(id), 1) + 10) from public.catalogo_analisis;
select setval(pg_get_serial_sequence('public.solicitudes_analisis', 'id'), coalesce(max(id), 1) + 10) from public.solicitudes_analisis;
