import { Activity, Bed, CalendarDays, ClipboardList, FileText, FlaskConical, LayoutDashboard, Stethoscope, UsersRound } from 'lucide-react'
import type { ModuleConfig, Row } from './types'

export const navItems = [['Resumen', LayoutDashboard], ['Citas', CalendarDays], ['Pacientes', UsersRound], ['Médicos', Stethoscope], ['Expedientes', FileText], ['Internación', Bed], ['Órdenes médicas', ClipboardList], ['Laboratorio', FlaskConical]] as const
export const appointments: Row[] = [['08:30', 'Mariana Torres', 'Dra. Ana López', 'Consulta general', 'Confirmada'], ['09:00', 'Carlos Ramírez', 'Dr. Jorge Méndez', 'Cardiología', 'En espera'], ['09:30', 'Sofía Hernández', 'Dra. Ana López', 'Seguimiento', 'Confirmada'], ['10:00', 'Roberto García', 'Dra. Laura Ruiz', 'Control clínico', 'Pendiente'], ['10:30', 'Lucía Martínez', 'Dr. Jorge Méndez', 'Cardiología', 'Confirmada']]

export const modules: Record<string, ModuleConfig> = {
  Citas: { icon: CalendarDays, eyebrow: 'Gestión de agenda', title: 'Citas médicas', description: 'Programa, confirma y da seguimiento a las consultas.', action: 'Nueva cita', columns: ['Hora', 'Paciente', 'Médico', 'Motivo', 'Estado'], rows: appointments },
  Pacientes: { icon: UsersRound, eyebrow: 'Directorio clínico', title: 'Pacientes', description: 'Administra datos e historial de tus pacientes.', action: 'Nuevo paciente', columns: ['Paciente', 'Identificación', 'Teléfono', 'Última visita', 'Estado'], rows: [['Mariana Torres', 'PAC-00124', '555 0182', '24 sep 2024', 'Activo'], ['Carlos Ramírez', 'PAC-00119', '555 0214', '22 sep 2024', 'Activo'], ['Sofía Hernández', 'PAC-00118', '555 0341', '19 sep 2024', 'Activo'], ['Roberto García', 'PAC-00111', '555 0890', '15 sep 2024', 'Inactivo']] },
  Médicos: { icon: Stethoscope, eyebrow: 'Personal médico', title: 'Médicos y especialistas', description: 'Consulta especialidades, horarios y disponibilidad.', action: 'Registrar médico', columns: ['Profesional', 'Especialidad', 'Consultorio', 'Horario', 'Estado'], rows: [['Dra. Ana López', 'Medicina general', 'Consultorio 01', '08:00 — 14:00', 'Disponible'], ['Dr. Jorge Méndez', 'Cardiología', 'Consultorio 03', '09:00 — 17:00', 'En consulta'], ['Dra. Laura Ruiz', 'Medicina interna', 'Consultorio 02', '10:00 — 18:00', 'Disponible']] },
  Expedientes: { icon: FileText, eyebrow: 'Historia clínica', title: 'Expedientes médicos', description: 'Registra consultas, diagnósticos, recetas y documentos.', action: 'Nuevo expediente', columns: ['Paciente', 'Última consulta', 'Diagnóstico', 'Médico responsable', 'Actualizado'], rows: [['Mariana Torres', 'Consulta general', 'Hipertensión controlada', 'Dra. Ana López', 'Hace 8 min'], ['Carlos Ramírez', 'Cardiología', 'Arritmia leve', 'Dr. Jorge Méndez', 'Ayer'], ['Sofía Hernández', 'Seguimiento', 'Sin hallazgos', 'Dra. Ana López', '19 sep']] },
  Internación: { icon: Bed, eyebrow: 'Hospitalización', title: 'Internación y camas', description: 'Controla habitaciones, admisiones, traslados y altas.', action: 'Nueva admisión', columns: ['Habitación', 'Paciente', 'Ingreso', 'Médico', 'Estado'], rows: [['Habitación 101', 'Roberto García', '23 sep 2024', 'Dra. Laura Ruiz', 'Ocupada'], ['Habitación 102', 'Elena Vargas', '22 sep 2024', 'Dr. Jorge Méndez', 'Ocupada'], ['Habitación 103', '—', '—', '—', 'Disponible'], ['Habitación 104', '—', '—', '—', 'Limpieza']] },
  'Órdenes médicas': { icon: ClipboardList, eyebrow: 'Indicaciones clínicas', title: 'Órdenes médicas', description: 'Revisa estudios, tratamientos y solicitudes pendientes.', action: 'Nueva orden', columns: ['Orden', 'Paciente', 'Médico', 'Tipo', 'Estado'], rows: [['ORD-0082', 'Carlos Ramírez', 'Dr. Jorge Méndez', 'Electrocardiograma', 'Pendiente'], ['ORD-0081', 'Mariana Torres', 'Dra. Ana López', 'Biometría hemática', 'En proceso'], ['ORD-0080', 'Sofía Hernández', 'Dra. Ana López', 'Radiografía', 'Completada']] },
  Laboratorio: { icon: FlaskConical, eyebrow: 'Resultados clínicos', title: 'Laboratorio', description: 'Gestiona solicitudes y entrega resultados de análisis.', action: 'Registrar resultado', columns: ['Muestra', 'Paciente', 'Estudio', 'Solicitado', 'Estado'], rows: [['LAB-0241', 'Carlos Ramírez', 'Biometría hemática', '24 sep 2024', 'Pendiente'], ['LAB-0240', 'Mariana Torres', 'Perfil lipídico', '23 sep 2024', 'Listo'], ['LAB-0239', 'Sofía Hernández', 'Glucosa', '23 sep 2024', 'En proceso']] },
}

export const dashboardStats = [{ icon: CalendarDays, label: 'Citas de hoy', value: '24', meta: '4 pendientes', tone: 'blue' }, { icon: UsersRound, label: 'Pacientes activos', value: '1,284', meta: '+12 esta semana', tone: 'violet' }, { icon: Bed, label: 'Camas ocupadas', value: '18 / 24', meta: '75% ocupación', tone: 'orange' }, { icon: Activity, label: 'Órdenes pendientes', value: '07', meta: '3 requieren atención', tone: 'green' }]
export const quickLinks = ['Registrar paciente', 'Ver resultados pendientes']

export function getModuleStats(active: string) { return [{ icon: modules[active]?.icon ?? Activity, label: 'Registros activos', value: active === 'Internación' ? '18' : active === 'Citas' ? '24' : '1,284', meta: 'Actualizado hoy', tone: 'blue' }, { icon: Activity, label: 'Pendientes', value: active === 'Laboratorio' ? '07' : '12', meta: 'Requieren atención', tone: 'orange' }, { icon: Activity, label: 'Completados hoy', value: '36', meta: '+8% esta semana', tone: 'green' }] }
