create extension if not exists btree_gist with schema public;

create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.usuarios
    where auth_user_id = (select auth.uid())
      and rol = 'admin'
      and esta_activo = true
  );
$$;

create table if not exists public.agenda_medicos (
  id bigint generated by default as identity primary key,
  medico_id bigint not null references public.perfiles_medicos(id) on delete cascade,
  dia_semana smallint not null,
  hora_inicio time not null,
  hora_fin time not null,
  duracion_slot integer not null default 20,
  esta_activo boolean not null default true,
  unique(medico_id, dia_semana, hora_inicio),
  constraint agenda_dia_valido check (dia_semana between 0 and 6),
  constraint agenda_horario_valido check (hora_fin > hora_inicio),
  constraint agenda_duracion_valida check (duracion_slot > 0 and duracion_slot <= 240)
);

create index if not exists idx_agenda_medicos_medico on public.agenda_medicos(medico_id, dia_semana);

alter table public.agenda_medicos enable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant all on table public.agenda_medicos to service_role;
grant select on table public.agenda_medicos to authenticated;
grant select on table public.agenda_medicos to anon;
grant all on all sequences in schema public to service_role, authenticated;
alter default privileges in schema public
  grant all on tables to service_role;
alter default privileges in schema public
  grant select on tables to authenticated;

drop policy if exists agenda_authenticated_select on public.agenda_medicos;
create policy agenda_authenticated_select on public.agenda_medicos for select to authenticated using (true);

drop policy if exists agenda_authenticated_manage on public.agenda_medicos;
create policy agenda_authenticated_manage on public.agenda_medicos for all to authenticated
  using (public.es_admin()) with check (public.es_admin());

alter table public.citas drop constraint if exists citas_no_traslape;
alter table public.citas add constraint citas_no_traslape exclude using gist (
  medico_id with =,
  tstzrange(inicio, fin) with &&
) where (estado in ('pendiente', 'confirmada'));

drop policy if exists authenticated_read_perfiles_medicos on public.perfiles_medicos;
create policy authenticated_read_perfiles_medicos on public.perfiles_medicos for select to authenticated using (true);

drop policy if exists authenticated_read_clinicas on public.clinicas;
create policy authenticated_read_clinicas on public.clinicas for select to authenticated using (true);

drop policy if exists authenticated_read_enfermeros on public.perfiles_enfermeros;
create policy authenticated_read_enfermeros on public.perfiles_enfermeros for select to authenticated using (true);

drop policy if exists usuarios_admin_insert on public.usuarios;
create policy usuarios_admin_insert on public.usuarios for insert to authenticated with check (public.es_admin());

drop policy if exists authenticated_read_usuarios on public.usuarios;
create policy authenticated_read_usuarios on public.usuarios for select to authenticated
  using (auth_user_id = (select auth.uid()) or public.es_admin());

drop policy if exists citas_authenticated_delete on public.citas;
create policy citas_authenticated_delete on public.citas for delete to authenticated
  using (public.es_admin());

insert into public.agenda_medicos (medico_id, dia_semana, hora_inicio, hora_fin, duracion_slot)
select m.id, d.dia_semana, '09:00'::time, '14:00'::time, 30
from public.perfiles_medicos m
cross join (values (1), (2), (3), (4), (5)) as d(dia_semana)
where m.esta_activo = true
on conflict (medico_id, dia_semana, hora_inicio) do nothing;

select m.id,
       (select nombre_completo from public.usuarios where id = m.usuario_id) as medico,
       m.especialidad,
       (select count(*) from public.agenda_medicos a where a.medico_id = m.id) as bloques_agenda
from public.perfiles_medicos m
order by m.id;
